# Generated by Django 3.0 on 2020-03-21 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0002_topcandidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcandidates',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
