# Generated by Django 3.2.7 on 2022-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0003_topcandidates_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
