# Generated by Django 3.2.7 on 2022-11-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0005_authority_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority_account',
            name='auth_userid',
        ),
        migrations.AddField(
            model_name='authority_account',
            name='id',
            field=models.AutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
