# Generated by Django 3.2.7 on 2022-11-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0006_auto_20221125_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority_account',
            name='id',
        ),
        migrations.AddField(
            model_name='authority_account',
            name='auth_userid',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
